<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_97431579577</name>
   <tag></tag>
   <elementGuidId>e5c10dde-94fa-4d96-9231-1d7f6a7a4be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'+97431579577')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.contactInfo_content_wrapper__mRoL6 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;+97431579577&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87bc277f-3736-4794-8eb0-620f9ed5b8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e7135705-814e-4d53-bf16-20e43c7f1501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wa.me/+97433229569</value>
      <webElementGuid>2a92130a-4916-4eb3-9113-c50657fe71be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+97431579577</value>
      <webElementGuid>df06064d-e581-4ec3-abc8-7ad338abe634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;inner_page offer-strip&quot;]/main[@class=&quot;technoblue-main&quot;]/div[@class=&quot;contactUs_contact_us___JNmP&quot;]/section[@class=&quot;contactInfo_contact_info_section__dbW6Y&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;contactInfo_contactInfo_list___zACV&quot;]/li[1]/div[@class=&quot;contactInfo_content_wrapper__mRoL6&quot;]/a[1]</value>
      <webElementGuid>04e413bf-dc88-40ad-b23d-7f864e948d67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+97431579577')]</value>
      <webElementGuid>b9f0e985-ae31-4515-8443-768593769633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::a[1]</value>
      <webElementGuid>87b8b33a-297d-4de7-b7a0-440979668115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>f6c36f02-f8ca-4b3e-8ecc-e74a9b104fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info@electronyat.qa'])[1]/preceding::a[2]</value>
      <webElementGuid>f696883e-d2c4-49f3-af1d-eae1aebee306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let’s get in touch'])[1]/preceding::a[3]</value>
      <webElementGuid>fc2165b2-b160-402f-ba27-18040e3d1167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+97431579577']/parent::*</value>
      <webElementGuid>219e3c3b-3ed3-462c-809f-5e91a31d57f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://wa.me/+97433229569')]</value>
      <webElementGuid>adc8371d-f353-41b2-880f-2e1139c74a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/a</value>
      <webElementGuid>b2385b99-5c92-4224-9e05-73b7761447dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wa.me/+97433229569' and (text() = '+97431579577' or . = '+97431579577')]</value>
      <webElementGuid>7dd9eba8-b959-4b09-9219-8a512301fe9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
