<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_message</name>
   <tag></tag>
   <elementGuidId>f3a99881-68ea-4996-b8f1-6746da17559d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='92203a11-d325-498a-a444-3cabbaaa9c7a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#92203a11-d325-498a-a444-3cabbaaa9c7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Your Message&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fb1b1e56-b30b-4094-81a3-4c09a91c2479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>c0680ca1-0e1c-4278-89c7-f1f904503921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Your Message</value>
      <webElementGuid>03c4b2c2-7aba-490e-975d-26b5c9caa809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>92203a11-d325-498a-a444-3cabbaaa9c7a</value>
      <webElementGuid>3427f6bd-340e-4bf5-aa13-fcea02e1aab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bdc670b5-183d-47d4-9ea7-bb97184506b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;92203a11-d325-498a-a444-3cabbaaa9c7a&quot;)</value>
      <webElementGuid>aa871e15-eb5b-4585-900d-e710b0eeb7a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='92203a11-d325-498a-a444-3cabbaaa9c7a']</value>
      <webElementGuid>685b471e-8271-4579-9d5b-ca6ce140e952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7084ee23-28a0-4795-b70f-8f5d7102e66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message' and @placeholder = 'Enter Your Message' and @id = '92203a11-d325-498a-a444-3cabbaaa9c7a']</value>
      <webElementGuid>a42e7fda-a66b-4b18-b506-8f7a2c4e93c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
