<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tes</name>
   <tag></tag>
   <elementGuidId>00d365a4-5101-482a-8412-7a2f6e1397c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='92203a11-d325-498a-a444-3cabbaaa9c7a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#92203a11-d325-498a-a444-3cabbaaa9c7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Your Message&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7878be6b-b8fa-464a-bbb2-2c4ef08f78e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>e27c5869-b854-452b-9eae-a43133a72bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Your Message</value>
      <webElementGuid>9c6e6701-d602-40c8-9cd3-1840695ec939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>92203a11-d325-498a-a444-3cabbaaa9c7a</value>
      <webElementGuid>2b70571c-365b-47af-b64e-28f3a589d975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3d788e62-f603-419c-b531-6d70e70dbd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tes</value>
      <webElementGuid>026c2d8f-0e18-4a75-93b5-f3d8b310701d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;92203a11-d325-498a-a444-3cabbaaa9c7a&quot;)</value>
      <webElementGuid>d076da85-2fb8-47e8-8591-5f6135596943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='92203a11-d325-498a-a444-3cabbaaa9c7a']</value>
      <webElementGuid>ca0a3df3-771d-4480-af2c-4cbddf07007a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message*'])[1]/following::textarea[1]</value>
      <webElementGuid>751b03cf-47ec-48a2-8465-c7c9ef09de4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8326fbd5-b7da-48ff-be1c-0f4eb8243616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Quote'])[1]/preceding::textarea[1]</value>
      <webElementGuid>061621bd-8c84-4aec-9813-aff1ad860a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tes']/parent::*</value>
      <webElementGuid>e1436812-d3f7-438f-8b1c-be47e670d103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>82345a8d-8d39-43b2-bba5-87203f667569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message' and @placeholder = 'Enter Your Message' and @id = '92203a11-d325-498a-a444-3cabbaaa9c7a' and (text() = 'Tes' or . = 'Tes')]</value>
      <webElementGuid>7020cc07-8ce9-44e8-b918-b3a75fa09e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
