<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_78 - Abu Dhalouf</name>
   <tag></tag>
   <elementGuidId>b2beda3d-0dbc-4c6b-9465-9114e8fd420a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;78 - Abu Dhalouf&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0b02f41-83d3-4276-9290-38d022840125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select__option custom-select__option--is-focused css-1rem6mv-option</value>
      <webElementGuid>7515cb79-6fab-4a53-8d00-2c5a7d39f65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e07b5f4-06b4-4a67-9c6a-5e5fdc73c9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-3</value>
      <webElementGuid>d1b6f159-3663-4ce1-b918-ea41e5684f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4846436-5a78-4452-8ce8-a5abf7a14cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>78 - Abu Dhalouf </value>
      <webElementGuid>4b7e6e4e-6311-4d06-8ef9-8067a6ba6ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-3&quot;)</value>
      <webElementGuid>0f4af728-73b1-4175-ad3b-ab79c404feeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-3']</value>
      <webElementGuid>0ec3a7a2-bd48-4584-9282-606a66c16307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div/div[4]</value>
      <webElementGuid>8c66708e-97a1-455f-bc3a-20a98471cdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zone Number*'])[1]/following::div[14]</value>
      <webElementGuid>28a8b84a-6b36-48e8-8521-3a359c916e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Number'])[1]/preceding::div[171]</value>
      <webElementGuid>2c183083-66b4-441b-bd47-05c0f764c335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='78 - Abu Dhalouf']/parent::*</value>
      <webElementGuid>ffcd8864-af45-461e-8ccb-cf573fdf9078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>f2f4c91c-4670-4ffd-ba7c-82b3bebf175b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-3' and (text() = '78 - Abu Dhalouf ' or . = '78 - Abu Dhalouf ')]</value>
      <webElementGuid>f0881c98-6e89-4394-bdad-cd7d961d11f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
