<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select  zone  number_custom-select__inp_25ea20</name>
   <tag></tag>
   <elementGuidId>45123422-4097-4c5c-bee0-0f59d3caafe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3431ffd6-eae9-41cf-ae62-ae5036a164ab']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.custom-select__input-container.css-19bb58m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.custom-select__input-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73091dc8-8842-427f-b163-20bd79451d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select__input-container css-19bb58m</value>
      <webElementGuid>750e2d82-dfa0-41ab-886d-4ad917b7cdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3431ffd6-eae9-41cf-ae62-ae5036a164ab&quot;)/div[@class=&quot;custom-select__control custom-select__control--is-focused custom-select__control--menu-is-open css-12oqisq-control&quot;]/div[@class=&quot;custom-select__value-container css-hlgwow&quot;]/div[@class=&quot;custom-select__input-container css-19bb58m&quot;]</value>
      <webElementGuid>f7bb9f8a-779e-4344-841b-f0c45e184601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3431ffd6-eae9-41cf-ae62-ae5036a164ab']/div/div/div[2]</value>
      <webElementGuid>723b949b-8cda-47a7-b5ae-dd29d8972d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zone Number*'])[1]/following::div[6]</value>
      <webElementGuid>7a88b4bc-c148-4652-aeb7-d114fc9465d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Number'])[1]/preceding::div[179]</value>
      <webElementGuid>a0a0bf31-e4f7-48c4-8eb3-219301ab0fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div[2]</value>
      <webElementGuid>42eb0129-581e-4889-96f6-bc8e9aad3082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
