<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_phone_number</name>
   <tag></tag>
   <elementGuidId>b3cfa4ce-66a4-4083-a654-affd1c26a172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d17f3721-aa5f-43cb-95ee-61d8e88433bd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d17f3721-aa5f-43cb-95ee-61d8e88433bd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;phone_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2132d9c8-545e-4bc2-b126-ae4827e7e003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3999ab17-e624-469c-9c3c-79af06925c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d17f3721-aa5f-43cb-95ee-61d8e88433bd</value>
      <webElementGuid>0b8569be-5100-4e91-9c2f-8f2d323f7a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>1650a0b6-9cb3-4f7f-a959-84deee459144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56390de8-b39a-4969-890f-80be665d4a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974</value>
      <webElementGuid>d477a782-196c-4ed4-bdcf-331b7051ada5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>b57c514c-62c5-4063-be91-7f3dcadc7e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d17f3721-aa5f-43cb-95ee-61d8e88433bd&quot;)</value>
      <webElementGuid>bb7701ff-d661-41e9-bf69-42048cdd9f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d17f3721-aa5f-43cb-95ee-61d8e88433bd']</value>
      <webElementGuid>97d6cf68-0ffc-4810-bb53-05e10a15ef9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>7a6e817e-ab70-4e21-adde-ef4fa4929e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd17f3721-aa5f-43cb-95ee-61d8e88433bd' and @type = 'text' and @name = 'phone_number']</value>
      <webElementGuid>afc08cbd-526f-4747-8e72-5664727bcb85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
