<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Morning</name>
   <tag></tag>
   <elementGuidId>95e0f22f-0c3d-473b-ad8d-2c517547ea0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.customDropDown_drop_down_link__7RYhs.selected.d-flex.align-items-center.drop_down_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Morning')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Morning&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>182938bc-052b-48af-9a4f-9c17c293f91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customDropDown_drop_down_link__7RYhs selected d-flex align-items-center  drop_down_link </value>
      <webElementGuid>056f66a3-4c63-47cb-9876-443603dd9fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Morning</value>
      <webElementGuid>91f0b693-0f4a-4a24-804b-da86f0cd0ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;inner_page modal-open&quot;]/div[@class=&quot;fade emptyAddressPage_add_address_form_modal__4uqYJ modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;createNewAddressForm_location_form__DTt49&quot;]/form[1]/div[@class=&quot;form-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;select-input customSelect_select_input__DUokL&quot;]/div[@class=&quot;customDropDown_dropdown_main_wrap__KWIv0 drop_down_wrap  dropdown&quot;]/a[@class=&quot;customDropDown_drop_down_link__7RYhs selected d-flex align-items-center  drop_down_link&quot;]</value>
      <webElementGuid>9ff62d24-b128-49c6-8666-68eba98e6e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Morning')]</value>
      <webElementGuid>0e290ea9-6884-44c7-888f-0e13f935dbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferred delivery time*'])[1]/following::a[1]</value>
      <webElementGuid>094b52c9-10cc-4c0a-a664-8eb11f3a0430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/preceding::a[1]</value>
      <webElementGuid>ea5a26f2-9b08-47d8-b605-defed4cdae6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Address*'])[1]/preceding::a[1]</value>
      <webElementGuid>52c1cb22-435a-49ed-901c-fa2ad34b5cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Morning']/parent::*</value>
      <webElementGuid>92426ff3-39f3-4faa-848b-b1004f36356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[104]</value>
      <webElementGuid>e714c9c1-16df-4a3b-ad78-b32fde62aa2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/a</value>
      <webElementGuid>60b29118-760e-41ef-b392-1dc67ea589cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Morning' or . = 'Morning')]</value>
      <webElementGuid>7f12ddcb-8a52-4294-85d0-a7395483a8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
