<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select  zone  number_custom-select__inp_25ea20</name>
   <tag></tag>
   <elementGuidId>f7c17df9-a9ec-4ffa-8fbc-fb9c71eb8c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.custom-select__input-container.css-19bb58m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='04219237-0ffc-48c7-b8e5-8d5703b354ce']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.custom-select__input-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ceb49680-2297-4bfe-86e7-b8778471b276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select__input-container css-19bb58m</value>
      <webElementGuid>3b42dd23-4884-413c-83f7-e46f168b62c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;04219237-0ffc-48c7-b8e5-8d5703b354ce&quot;)/div[@class=&quot;custom-select__control custom-select__control--is-focused custom-select__control--menu-is-open css-12oqisq-control&quot;]/div[@class=&quot;custom-select__value-container css-hlgwow&quot;]/div[@class=&quot;custom-select__input-container css-19bb58m&quot;]</value>
      <webElementGuid>9497cb87-5d28-4a0d-86b3-a1a2c98370d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='04219237-0ffc-48c7-b8e5-8d5703b354ce']/div/div/div[2]</value>
      <webElementGuid>47ac5af9-93e0-4b26-8a79-9cdaa198586f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zone Number*'])[1]/following::div[6]</value>
      <webElementGuid>712f4cae-4f66-4fce-bd80-04bf1046028d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Number'])[1]/preceding::div[179]</value>
      <webElementGuid>fbfe5477-464d-466f-b1c8-ba84b7df7af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]</value>
      <webElementGuid>1eab7bbd-0c24-4794-b973-2d0e5394a6ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
