<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_phone_number_1</name>
   <tag></tag>
   <elementGuidId>acb3b883-310d-4ca2-886d-219e096585e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7b88bc55-3a36-481e-9fc4-87b47731440e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7b88bc55-3a36-481e-9fc4-87b47731440e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;phone_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9995014-d344-4846-ba18-0291d082192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>74422f2b-6511-4e36-b0ff-d2ddbe2859e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7b88bc55-3a36-481e-9fc4-87b47731440e</value>
      <webElementGuid>00f7cb7a-b93d-4e1c-b3e5-58874ea47790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>5ca5b462-3a45-477b-b700-b21358156247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bdf4a5c-6320-47c5-aa32-604c0f0d1b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974 5645 23</value>
      <webElementGuid>3ffa8a69-fc04-41b1-8363-a45e6a24513b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>0c237f39-b9bf-4799-95af-f99fd58baca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7b88bc55-3a36-481e-9fc4-87b47731440e&quot;)</value>
      <webElementGuid>775d48af-f4f3-44ae-857f-b593391ab941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7b88bc55-3a36-481e-9fc4-87b47731440e']</value>
      <webElementGuid>a663ccac-1224-4f90-a86e-c9974f4bc440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>6f5e9bc2-040c-4c69-995f-a39b1862d4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7b88bc55-3a36-481e-9fc4-87b47731440e' and @type = 'text' and @name = 'phone_number']</value>
      <webElementGuid>44deb89e-f187-44f6-9101-27c5771d48a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
