<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Office_90b6fe6b-569f-42aa-9c8e-9867d698897c</name>
   <tag></tag>
   <elementGuidId>7d1e486d-f2d0-49ab-9834-0467dcbfc305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#90b6fe6b-569f-42aa-9c8e-9867d698897c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='90b6fe6b-569f-42aa-9c8e-9867d698897c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Default address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e657d0c3-1109-498c-b835-bbf569ccd912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>90b6fe6b-569f-42aa-9c8e-9867d698897c</value>
      <webElementGuid>98a230c6-3400-4802-87c3-de5886258f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d5b6460a-2a33-4300-9b61-538973364213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f259b0c2-4110-4b2e-9f10-c2a3f506fa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;90b6fe6b-569f-42aa-9c8e-9867d698897c&quot;)</value>
      <webElementGuid>c0949f63-d632-4940-b644-7c19c6dd9154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='90b6fe6b-569f-42aa-9c8e-9867d698897c']</value>
      <webElementGuid>185b98a3-36e5-4852-b5fc-561a3abe6fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>23f8a0c8-45ee-49bd-b7e5-c68042354e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '90b6fe6b-569f-42aa-9c8e-9867d698897c' and @type = 'checkbox']</value>
      <webElementGuid>db4a62b6-75ed-4a6b-b7d5-4f15dbc42550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
