<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_phone_number</name>
   <tag></tag>
   <elementGuidId>58ca5415-4d4a-4d9e-9e95-8788fca07608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3b4372eb-c1ef-4f72-8f1c-69b081064ed1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3b4372eb-c1ef-4f72-8f1c-69b081064ed1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;phone_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fb8cadd-0b68-40a1-b9e5-9c436bd7d5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8a677fb1-2446-424a-83be-8839c6faae61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3b4372eb-c1ef-4f72-8f1c-69b081064ed1</value>
      <webElementGuid>c681ff99-c30a-4754-aae8-b97f79cb2d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>3162aca1-245c-42b9-87da-53bd9a74304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2f20e6a-f605-4bcf-bfb0-d3c2549130cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974 5755 7562</value>
      <webElementGuid>68f535a7-56d9-431f-9778-dc85e4b5d8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>bcd4b1a0-21e7-4ca0-9806-657308a9a6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3b4372eb-c1ef-4f72-8f1c-69b081064ed1&quot;)</value>
      <webElementGuid>352958ed-bbc9-4c05-8862-fd84a7488f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3b4372eb-c1ef-4f72-8f1c-69b081064ed1']</value>
      <webElementGuid>bf90fd50-d723-45e2-a80a-8cd6e8834760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>d87c7d9c-f3c8-4516-9358-34b2bf3c6f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3b4372eb-c1ef-4f72-8f1c-69b081064ed1' and @type = 'text' and @name = 'phone_number']</value>
      <webElementGuid>b299f2c5-044b-4173-b5f5-4193e28e9b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
