<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alternate Number_alternate_number</name>
   <tag></tag>
   <elementGuidId>d8fc7d68-4db1-4368-af6c-44236985c28e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#334e863b-245a-4923-8f47-37e835fa8f64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='334e863b-245a-4923-8f47-37e835fa8f64']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;alternate_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85795430-3232-4679-81bd-e7b997c4e571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>11d9abcf-815d-46ad-bcd9-bb84cff9e1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>334e863b-245a-4923-8f47-37e835fa8f64</value>
      <webElementGuid>b69b7803-60ff-4285-85a0-5a6c5915bee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>167554b7-870f-48d7-8f3c-7246964a0dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eba199b3-a8fa-40ec-9fe3-7c604efa4610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974</value>
      <webElementGuid>9435d687-f440-4945-8a98-a5fdb30034d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alternate_number</value>
      <webElementGuid>e8a330c4-1052-4613-aa15-dd82cd8330f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;334e863b-245a-4923-8f47-37e835fa8f64&quot;)</value>
      <webElementGuid>dbd1f1c4-0935-4858-8123-b6cb9b74144b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='334e863b-245a-4923-8f47-37e835fa8f64']</value>
      <webElementGuid>57b9e32a-1c89-4caa-b167-fe02416a4c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>ac0372f2-e0cc-42d0-8323-e11e891b5e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '334e863b-245a-4923-8f47-37e835fa8f64' and @type = 'text' and @name = 'alternate_number']</value>
      <webElementGuid>3c032dc5-0bce-4198-a015-e343b416a1d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
