<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alternate Number_alternate_number_1</name>
   <tag></tag>
   <elementGuidId>d5f0f17c-2226-4cf3-86ee-3d5b975e1c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e85ba16c-55d6-423c-a746-d2dc0825531e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e85ba16c-55d6-423c-a746-d2dc0825531e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;alternate_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f632f0e-4943-4223-843b-acf9b7994698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>58e70f21-0056-4669-abe5-4c8eaec19c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e85ba16c-55d6-423c-a746-d2dc0825531e</value>
      <webElementGuid>81a75b73-8cea-4f50-9b2f-e26ae5109ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>27cc6808-a23d-46be-9a96-e8633fe38a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21f11aff-b19b-498e-8615-971e501efae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974 6398 52</value>
      <webElementGuid>6d30bd3c-44e5-4bf1-9df3-167cacf13d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alternate_number</value>
      <webElementGuid>aaeefb84-cca1-442c-aa1f-3906db77cb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e85ba16c-55d6-423c-a746-d2dc0825531e&quot;)</value>
      <webElementGuid>84bfb519-14bc-4b60-930f-288349482df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e85ba16c-55d6-423c-a746-d2dc0825531e']</value>
      <webElementGuid>2a259bfb-5b83-4da2-8440-410569b231b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>ed8e1a09-9ab8-41ee-9b7c-afb3ac1aa2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e85ba16c-55d6-423c-a746-d2dc0825531e' and @type = 'text' and @name = 'alternate_number']</value>
      <webElementGuid>08dcf2f0-cbb2-44e8-8210-9054781d5fc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
