<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_What are you looking for_loaded image</name>
   <tag></tag>
   <elementGuidId>465a5151-6667-4687-9f9f-0ea7907870ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Technoblue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.loaded.image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Technoblue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ae31b24-cb8b-4191-b27b-f8134d0706aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Technoblue</value>
      <webElementGuid>879e673f-2e61-4d14-adac-8d311d495ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Technoblue</value>
      <webElementGuid>1fbfc082-8e74-44cc-97ad-dba23934a2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>8f59a1aa-0a6f-42e3-9195-b41f7a947fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>5631ec5b-a84d-4022-9293-fd53d2423f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>b2dcf7df-7b64-4d62-94b4-a1d517d4d0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7c07f3d2-f103-423b-a2b6-d127d1cf27e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>135771b4-5fb0-411e-8e0e-ddb5b44f9be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loaded image</value>
      <webElementGuid>9e2eff70-6d0a-4726-8253-60c9ab667499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/electronyat.8bc70f46.svg</value>
      <webElementGuid>4c1ed9d3-3131-490b-bdf1-53c2a3eee37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;inner_page&quot;]/header[@class=&quot;header_header__P90l2 header&quot;]/div[@class=&quot;header_header_middile_wrap__Bq9eX&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header_main_wrap__VaeFa&quot;]/a[@class=&quot;logo_logo__x10mm&quot;]/img[@class=&quot;loaded image&quot;]</value>
      <webElementGuid>123e727b-8f76-433a-ab5a-372d04099c0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Technoblue']</value>
      <webElementGuid>47ec90c2-bcb1-4627-967f-2a95059374e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f14a2ed2-4050-49be-9ffd-946d7d9d97f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Technoblue' and @alt = 'Technoblue' and @src = '/_next/static/media/electronyat.8bc70f46.svg']</value>
      <webElementGuid>72512209-1f77-4e10-baf3-d1e43e42dea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
