<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_user_name</name>
   <tag></tag>
   <elementGuidId>30ce374e-f5d6-41e7-b12c-89c0d10e762c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='68ab862c-9538-4601-bf16-fd24abe26b74']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#68ab862c-9538-4601-bf16-fd24abe26b74</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Phone Number AfghanistanÅland IslandsAlbaniaAlgeriaAmerican SamoaAndorraAngolaAn&quot;i >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a67fc80-687c-4193-b3ce-d4b8454b6c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8a1080a7-7d0a-44eb-9b2d-b2718fa014d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>68ab862c-9538-4601-bf16-fd24abe26b74</value>
      <webElementGuid>27319a70-9fe1-4466-938a-4700333aa97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PhoneInputInput</value>
      <webElementGuid>b054e123-d3ed-4680-bb24-9593772f77d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>263753d3-bd31-49cd-9b7f-67603104d3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+974 5755 756</value>
      <webElementGuid>0af2d008-9608-4088-93f7-2973ddc3c3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>ab52e862-3d8b-4a55-a989-23774f2800a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;68ab862c-9538-4601-bf16-fd24abe26b74&quot;)</value>
      <webElementGuid>8e9c2735-18a1-42e1-861e-f3253be104e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='68ab862c-9538-4601-bf16-fd24abe26b74']</value>
      <webElementGuid>3872789a-4972-4381-a4ed-43df2ba16146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/div/div/div/input</value>
      <webElementGuid>51c5adc9-9ce2-4c48-8417-e5d19a015f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '68ab862c-9538-4601-bf16-fd24abe26b74' and @type = 'text' and @name = 'user_name']</value>
      <webElementGuid>354ab184-ef63-4afc-b35d-269f17e2a5f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
