<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_user_name</name>
   <tag></tag>
   <elementGuidId>cc0b9ca2-762a-4cdd-ad70-90066ad83007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter email address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5f84f7f-3f86-49a5-a895-75bd48c7d8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email address</value>
      <webElementGuid>ff9f79cb-99aa-46dd-bd1e-58236c228461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d88d3d05-e385-4ad1-8cf8-bcf6478308c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>156276e4-cea7-42af-a104-26acdd69133b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>aswathi.s+22@webandcrafts.com</value>
      <webElementGuid>e600f1b5-1c5c-4ee0-8dcc-1c2085d72b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>9c4178d3-f118-473c-b109-3ce1bb5fba9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;inner_page&quot;]/main[@class=&quot;technoblue-main&quot;]/aside[@class=&quot;layout_account_layout__b_9_s&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;layout_account_layout_wrapper___uz5N&quot;]/div[@class=&quot;layout_account_layout_content__5vlt7&quot;]/div[@class=&quot;profile_profile__54L7b&quot;]/div[@class=&quot;profile_account_info_form__jSZ1b form-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;accountInfoUpdate_account_info_update__fv8DH&quot;]/form[1]/div[@class=&quot;form_field_wrapper&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;textInput_text_input__v0Upl text_input&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>8d42c832-32e4-4d41-a53a-afd9370443f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user_name']</value>
      <webElementGuid>c05dfc64-86aa-459a-a521-4244caf5912a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>51a219c7-3555-4f15-b4f3-b9d43006810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter email address' and @name = 'user_name']</value>
      <webElementGuid>0ee54983-da36-4fc4-932e-ac71d208616f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
