<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Webandcrafts_yarl__slide_image</name>
   <tag></tag>
   <elementGuidId>1000cdb4-36e4-474a-bbe0-1453d00a9b57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.yarl__slide.yarl__slide_current.yarl__flex_center > div.yarl__fullsize.yarl__flex_center.yarl__slide_wrapper > img.yarl__slide_image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='magnify_image_wrap']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bc36af5-1edd-4a5b-821d-8163b15c0dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>123712ca-a7f6-4852-9c64-26eee8a7009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yarl__slide_image</value>
      <webElementGuid>52f5383f-6c3b-4e46-a700-e8f6c6c96d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat-backend.electronyat.qa/media/catalog/product/cache/518e522bac1df92102d4b2a1c65a4531/0/0/0019608_samsung-galaxy-a05s-4gb-ram-128gb-black_1_1.jpeg</value>
      <webElementGuid>458411bc-ca39-41b4-9f6f-a9cb6c8c4b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;offer-strip inner_page yarl__no_scroll&quot;]/div[@class=&quot;yarl__root yarl__portal yarl__no_scroll_padding yarl__portal_open&quot;]/div[@class=&quot;yarl__container yarl__flex_center&quot;]/div[@class=&quot;yarl__carousel yarl__carousel_with_slides&quot;]/div[@class=&quot;yarl__slide yarl__slide_current yarl__flex_center&quot;]/div[@class=&quot;yarl__fullsize yarl__flex_center yarl__slide_wrapper&quot;]/img[@class=&quot;yarl__slide_image&quot;]</value>
      <webElementGuid>10a72af9-dfc8-4446-92ff-ab96ba4efd9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://uat-backend.electronyat.qa/media/catalog/product/cache/518e522bac1df92102d4b2a1c65a4531/0/0/0019608_samsung-galaxy-a05s-4gb-ram-128gb-black_1_1.jpeg')])[2]</value>
      <webElementGuid>0c2b64c3-e625-470f-9200-39af04c82d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/img</value>
      <webElementGuid>7551a1e6-ac64-41bd-9945-25fa62f2714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat-backend.electronyat.qa/media/catalog/product/cache/518e522bac1df92102d4b2a1c65a4531/0/0/0019608_samsung-galaxy-a05s-4gb-ram-128gb-black_1_1.jpeg']</value>
      <webElementGuid>f4bd91cc-eff5-4369-926a-d0bcae183c48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
