<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_infoelectronyat.qa</name>
   <tag></tag>
   <elementGuidId>bb11160b-46d5-437c-ae81-b2612b8b5776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'info@electronyat.qa')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.accordion-collapse.collapse.show > div.accordion-body > div > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;info@electronyat.qa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>338e35c6-fae9-4f14-90d5-fdf110f54dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:info@electronyat.qa</value>
      <webElementGuid>f7d39c84-93c1-4cb6-bbea-3e5cbb4130dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>info@electronyat.qa</value>
      <webElementGuid>ccdd817e-b572-4d67-9427-c5314a6b51f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;inner_page offer-strip&quot;]/main[@class=&quot;technoblue-main&quot;]/div[@class=&quot;faq_faq__8zTaY&quot;]/form[1]/div[@class=&quot;container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/p[1]/a[1]</value>
      <webElementGuid>0e70043a-3f1d-4b59-8fe4-99bfc20009a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'info@electronyat.qa')]</value>
      <webElementGuid>828e97c9-3186-45de-ac1b-5473cd8021a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are all the checkout limits?'])[1]/following::a[1]</value>
      <webElementGuid>88716ab4-c990-4acd-b904-a3c32d27a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@electronyat.qa'])[1]/following::a[1]</value>
      <webElementGuid>38cfcd90-52f4-443a-a12d-0c2cb7e1cde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How can I track my orders &amp; payments?'])[1]/preceding::a[1]</value>
      <webElementGuid>85fbf8f1-b1f0-4583-9e10-06938350a5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@electronyat.qa'])[2]/preceding::a[1]</value>
      <webElementGuid>09afbc0f-9a9f-4ea0-a574-4c52b13a625d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='info@electronyat.qa']/parent::*</value>
      <webElementGuid>3e2297f2-27a9-447f-9cb1-872f0b15d41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'mailto:info@electronyat.qa')])[2]</value>
      <webElementGuid>c8c97b74-9339-4403-b284-464cad1cbabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p/a</value>
      <webElementGuid>af3d41f5-e9af-4216-a816-a90f1a181d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:info@electronyat.qa' and (text() = 'info@electronyat.qa' or . = 'info@electronyat.qa')]</value>
      <webElementGuid>6c25039f-5a5d-4aa8-945c-e12b571f4330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
